source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '12.0'

target 'LgBaseSDK_Example' do
  pod 'LgBaseSDK', :path => '../'

  target 'LgBaseSDK_Tests' do
    inherit! :search_paths

    
  end
end

